# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration - Testing for HTML elements

on:
  push:
    branches:
      - continuous-integration

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Create node_modules file path
      run: |
        mkdir /home/runner/work/Go-Mechanic/node_modules
        
    - name: Install dependencies
      run: npm install --force
  #    working-directory: /home/runner/work/Go-Mechanic/node_modules
      
    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: ./node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: build
      run: npm run build:ci
      
    - name: Running Anthony's Unit Tests
      run: npm run test:ci
      
    - name: Running Joseph's Unit Tests
      run: npm run test:sam
      
    - name: Running Jim's Unit Tests
      run: npm run test:jim
